import { Student } from './student';

export const STUDENTS: Student[] = [
  {firstName: 'Tabitha', lastName: 'Simon', birthDate: new Date(2015, 2, 27), averageScore: 4, id: 1},
  {firstName: 'Walter', lastName: 'Sullivan', birthDate: new Date(1995, 5, 16), averageScore: 2, id: 2},
  {firstName: 'Fabian', lastName: 'Doe', birthDate: new Date(1999, 10, 5), averageScore: 4, id: 3},
  {firstName: 'Noah', lastName: 'Beck', birthDate: new Date(2001, 7, 5), averageScore: 2, id: 4},
  {firstName: 'Vanessa', lastName: 'Alvarado', birthDate: new Date(1995, 5, 5), averageScore: 4, id: 5},
  {firstName: 'Ed', lastName: 'Stewart', birthDate: new Date(1995, 5, 5), averageScore: 1, id: 6},
  {firstName: 'Belinda', lastName: 'Alvarado', birthDate: new Date(1995, 5, 5), averageScore: 3, id: 7},
  {firstName: 'Brandy', lastName: 'Wade', birthDate: new Date(2015, 8, 4), averageScore: 2, id: 8},
  {firstName: 'Fabian', lastName: 'Beck', birthDate: new Date(2011, 5, 23), averageScore: 5, id: 9},
  {firstName: 'Charlene', lastName: 'Doe', birthDate: new Date(2005, 3, 5), averageScore: 5, id: 10},
  {firstName: 'Harry', lastName: 'Ramirez', birthDate: new Date(2001, 5, 28), averageScore: 3, id: 11},
  {firstName: 'Noah', lastName: 'Sullivan', birthDate: new Date(1995, 9, 5), averageScore: 2, id: 12},
  {firstName: 'Tabitha', lastName: 'Carpenter', birthDate: new Date(2001, 8, 27), averageScore: 4, id: 13},
  {firstName: 'Walter', lastName: 'Ramirez', birthDate: new Date(2015, 5, 5), averageScore: 2, id: 14},
  {firstName: 'Charlene', lastName: 'Doe', birthDate: new Date(2011, 10, 18), averageScore: 4, id: 15},
  {firstName: 'Noah', lastName: 'Simon', birthDate: new Date(1995, 10, 13), averageScore: 2, id: 16},
  {firstName: 'Walter', lastName: 'Stokes', birthDate: new Date(1999, 5, 15), averageScore: 4, id: 17},
  {firstName: 'Ed', lastName: 'Doe', birthDate: new Date(1995, 5, 5), averageScore: 1, id: 18},
  {firstName: 'Belinda', lastName: 'Alvarado', birthDate: new Date(1995, 2, 5), averageScore: 3, id: 19},
  {firstName: 'Kyle', lastName: 'Doe', birthDate: new Date(1995, 5, 5), averageScore: 2, id: 20},
  {firstName: 'Brandy', lastName: 'Stewart', birthDate: new Date(1999, 1, 5), averageScore: 5, id: 21},
  {firstName: 'Gabriel', lastName: 'Wade', birthDate: new Date(2011, 5, 11), averageScore: 5, id: 22},
  {firstName: 'Vanessa', lastName: 'Ramirez', birthDate: new Date(2015, 20, 5), averageScore: 3, id: 23},
  {firstName: 'Noah', lastName: 'Stokes', birthDate: new Date(2001, 11, 15), averageScore: 2, id: 24},
  {firstName: 'Tabitha', lastName: 'Carpenter', birthDate: new Date(2005, 8, 2), averageScore: 4, id: 25},
  {firstName: 'Charlene', lastName: 'Sullivan', birthDate: new Date(2005, 4, 9), averageScore: 2, id: 26},
  {firstName: 'Kyle', lastName: 'Doe', birthDate: new Date(2011, 10, 8), averageScore: 4, id: 27},
  {firstName: 'Noah', lastName: 'Beck', birthDate: new Date(2005, 6, 5), averageScore: 2, id: 28},
  {firstName: 'Walter', lastName: 'Alvarado', birthDate: new Date(1995, 5, 4), averageScore: 4, id: 29},
  {firstName: 'Ed', lastName: 'Doe', birthDate: new Date(1995, 8, 5), averageScore: 1, id: 30},
  {firstName: 'Belinda', lastName: 'Alvarado', birthDate: new Date(1995, 5, 3), averageScore: 3, id: 31},
  {firstName: 'Kyle', lastName: 'Doe', birthDate: new Date(2005, 1, 5), averageScore: 2, id: 32},
  {firstName: 'Fabian', lastName: 'Beck', birthDate: new Date(1999, 5, 10), averageScore: 5, id: 33},
  {firstName: 'Vanessa', lastName: 'Simon', birthDate: new Date(2015, 2, 22), averageScore: 5, id: 34},
  {firstName: 'Brandy', lastName: 'Ramirez', birthDate: new Date(2011, 5, 1), averageScore: 3, id: 35},
  {firstName: 'Noah', lastName: 'Wade', birthDate: new Date(2001, 3, 12), averageScore: 2, id: 36}
];
